#!/bin/bash
# 创建占位符音效文件（非常小的静音 MP3）

# 这是一个最小的有效 MP3 文件（静音，约 0.1 秒）
# 使用 base64 编码的 MP3 数据
PLACEHOLDER_BASE64="//uQxAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAADhAC7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7//////////////////////////////////////////////////////////////////////////////////////////////////8AAABQTEFNRTMuMTAwBLUAAAAAAAAAABUgJANgQQABzAAABISwpzloAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+xDEAAPAAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABAAAAGkAAAAIAAANIAAAAQAAAaQAAAAg"

# 创建所有音效文件
for file in notification.mp3 warning.mp3 error.mp3 critical.mp3; do
    echo "$PLACEHOLDER_BASE64" | base64 -d > "$file"
    echo "✅ Created placeholder: $file"
done

echo ""
echo "占位符音效文件已创建！"
echo "这些是静音文件，可以正常工作但不会发出声音。"
echo "如需真实音效，请参考 README.md 中的下载链接。"
