"""
统一的验证限制常量
与前端保持一致，确保前后端验证规则对齐
"""

# 用户相关
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 100
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
EMAIL_MAX_LENGTH = 255
FULL_NAME_MAX_LENGTH = 100

# 内容相关
COMMENT_MAX_LENGTH = 1000
DANMAKU_MAX_LENGTH = 100
TITLE_MAX_LENGTH = 500
DESCRIPTION_MAX_LENGTH = 2000
BIOGRAPHY_MAX_LENGTH = 1000
PERSON_NAME_MAX_LENGTH = 200

# 特定内容
BANNER_TITLE_MAX_LENGTH = 200
BANNER_DESCRIPTION_MAX_LENGTH = 500
ANNOUNCEMENT_TITLE_MAX_LENGTH = 200
ANNOUNCEMENT_CONTENT_MAX_LENGTH = 2000
SERIES_NAME_MAX_LENGTH = 500
FOLDER_NAME_MAX_LENGTH = 200
FOLDER_DESCRIPTION_MAX_LENGTH = 500
SHARE_TITLE_MAX_LENGTH = 200
SHARE_DESCRIPTION_MAX_LENGTH = 1000

# URL和文件
URL_MAX_LENGTH = 2048
FILENAME_MAX_LENGTH = 255
IP_REASON_MAX_LENGTH = 500

# 数值范围
YEAR_MIN = 1900
YEAR_MAX = 2100
RATING_MIN = 0.0
RATING_MAX = 10.0
FONT_SIZE_MIN = 12
FONT_SIZE_MAX = 36
SORT_ORDER_MIN = -99999
SORT_ORDER_MAX = 99999

# 分页
PAGE_SIZE_MIN = 1
PAGE_SIZE_MAX = 100
PAGE_SIZE_DEFAULT = 20

# 验证限制字典（便于导入）
VALIDATION_LIMITS = {
    "USERNAME": {"min": USERNAME_MIN_LENGTH, "max": USERNAME_MAX_LENGTH},
    "PASSWORD": {"min": PASSWORD_MIN_LENGTH, "max": PASSWORD_MAX_LENGTH},
    "EMAIL": {"max": EMAIL_MAX_LENGTH},
    "COMMENT": {"max": COMMENT_MAX_LENGTH},
    "DANMAKU": {"max": DANMAKU_MAX_LENGTH},
    "TITLE": {"max": TITLE_MAX_LENGTH},
    "DESCRIPTION": {"max": DESCRIPTION_MAX_LENGTH},
    "BIOGRAPHY": {"max": BIOGRAPHY_MAX_LENGTH},
    "PERSON_NAME": {"max": PERSON_NAME_MAX_LENGTH},
    "URL": {"max": URL_MAX_LENGTH},
    "BANNER_TITLE": {"max": BANNER_TITLE_MAX_LENGTH},
    "BANNER_DESCRIPTION": {"max": BANNER_DESCRIPTION_MAX_LENGTH},
    "ANNOUNCEMENT_TITLE": {"max": ANNOUNCEMENT_TITLE_MAX_LENGTH},
    "ANNOUNCEMENT_CONTENT": {"max": ANNOUNCEMENT_CONTENT_MAX_LENGTH},
    "SERIES_NAME": {"max": SERIES_NAME_MAX_LENGTH},
    "FOLDER_NAME": {"max": FOLDER_NAME_MAX_LENGTH},
}

