"""add_media_version_model

Revision ID: 04ae0c4b8a16
Revises: 0f8081e0e8d0
Create Date: 2025-10-12 22:49:57.296641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ae0c4b8a16'
down_revision: Union[str, None] = '0f8081e0e8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='文件存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('url', sa.String(length=512), nullable=True, comment='访问URL'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽度(像素)'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高度(像素)'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='时长(秒)'),
    sa.Column('change_note', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='上传者ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_versions_id'), 'media_versions', ['id'], unique=False)
    op.create_index(op.f('ix_media_versions_media_id'), 'media_versions', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_versions_media_id'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_id'), table_name='media_versions')
    op.drop_table('media_versions')
    # ### end Alembic commands ###
