"""add_video_share_table

Revision ID: 4d03e9e72b44
Revises: 9e912ccc1af8
Create Date: 2025-10-10 09:11:38.223965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d03e9e72b44'
down_revision: Union[str, None] = '9e912ccc1af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('WECHAT', 'WEIBO', 'QQ', 'QZONE', 'TWITTER', 'FACEBOOK', 'LINK', 'OTHER', name='shareplatform'), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_shares_id'), 'video_shares', ['id'], unique=False)
    op.create_index(op.f('ix_video_shares_platform'), 'video_shares', ['platform'], unique=False)
    op.create_index(op.f('ix_video_shares_shared_at'), 'video_shares', ['shared_at'], unique=False)
    op.create_index(op.f('ix_video_shares_user_id'), 'video_shares', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_shares_video_id'), 'video_shares', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_shares_video_id'), table_name='video_shares')
    op.drop_index(op.f('ix_video_shares_user_id'), table_name='video_shares')
    op.drop_index(op.f('ix_video_shares_shared_at'), table_name='video_shares')
    op.drop_index(op.f('ix_video_shares_platform'), table_name='video_shares')
    op.drop_index(op.f('ix_video_shares_id'), table_name='video_shares')
    op.drop_table('video_shares')
    # ### end Alembic commands ###
