"""add_composite_indexes_for_performance

Revision ID: 572567d54b16
Revises: 4d03e9e72b44
Create Date: 2025-10-10 09:29:09.225404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572567d54b16'
down_revision: Union[str, None] = '4d03e9e72b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 复合索引: videos(status, created_at DESC)
    # 用于: 获取已发布视频列表,按时间排序
    op.create_index(
        'idx_videos_status_created',
        'videos',
        ['status', sa.text('created_at DESC')],
        unique=False
    )

    # 复合索引: comments(video_id, created_at DESC)
    # 用于: 获取视频评论,按时间排序
    op.create_index(
        'idx_comments_video_created',
        'comments',
        ['video_id', sa.text('created_at DESC')],
        unique=False
    )

    # 复合索引: comments(video_id, is_pinned DESC, created_at DESC)
    # 用于: 获取视频评论,置顶优先,按时间排序
    op.create_index(
        'idx_comments_video_pinned_created',
        'comments',
        ['video_id', sa.text('is_pinned DESC'), sa.text('created_at DESC')],
        unique=False
    )

    # 复合索引: favorites(user_id, created_at DESC)
    # 用于: 获取用户收藏,按时间排序
    op.create_index(
        'idx_favorites_user_created',
        'favorites',
        ['user_id', sa.text('created_at DESC')],
        unique=False
    )

    # 复合索引: watch_history(user_id, updated_at DESC)
    # 用于: 获取用户观看历史,按最后更新时间排序
    op.create_index(
        'idx_watch_history_user_updated',
        'watch_history',
        ['user_id', sa.text('updated_at DESC')],
        unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watch_history_user_updated', table_name='watch_history')
    op.drop_index('idx_favorites_user_created', table_name='favorites')
    op.drop_index('idx_comments_video_pinned_created', table_name='comments')
    op.drop_index('idx_comments_video_created', table_name='comments')
    op.drop_index('idx_videos_status_created', table_name='videos')
    # ### end Alembic commands ###
