"""add_upload_sessions_table_only

Revision ID: 5fb824f18e42
Revises: ai_enhanced_001
Create Date: 2025-10-14 16:12:52.553911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb824f18e42'
down_revision: Union[str, None] = 'ai_enhanced_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('upload_id', sa.String(length=64), nullable=False, comment='上传会话ID（UUID）'),
        sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
        sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件总大小（字节）'),
        sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
        sa.Column('chunk_size', sa.Integer(), nullable=True, comment='分块大小（默认5MB）'),
        sa.Column('total_chunks', sa.Integer(), nullable=False, comment='总分块数'),
        sa.Column('uploaded_chunks', sa.JSON(), nullable=True, comment='已上传的分块索引列表'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='媒体标题'),
        sa.Column('description', sa.String(length=1000), nullable=True, comment='媒体描述'),
        sa.Column('parent_id', sa.Integer(), nullable=True, comment='父文件夹ID'),
        sa.Column('tags', sa.String(length=512), nullable=True, comment='标签'),
        sa.Column('temp_dir', sa.String(length=512), nullable=False, comment='临时分块存储目录'),
        sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否完成'),
        sa.Column('is_merged', sa.Boolean(), nullable=True, comment='是否已合并'),
        sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传者ID'),
        sa.Column('media_id', sa.Integer(), nullable=True, comment='完成后的媒体ID'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后更新时间'),
        sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
        sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['media.id'], ),
        sa.ForeignKeyConstraint(['uploader_id'], ['admin_users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_id'), 'upload_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_upload_id'), 'upload_sessions', ['upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sessions_upload_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
