"""add_series_model_for_video_collections

Revision ID: 671ba508d174
Revises: 572567d54b16
Create Date: 2025-10-10 09:49:51.097026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671ba508d174'
down_revision: Union[str, None] = '572567d54b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comments_video_created', table_name='comments')
    op.drop_index('idx_comments_video_pinned_created', table_name='comments')
    op.drop_index('idx_favorites_user_created', table_name='favorites')
    op.drop_index('idx_videos_status_created', table_name='videos')
    op.drop_index('idx_watch_history_user_updated', table_name='watch_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_watch_history_user_updated', 'watch_history', ['user_id', sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_videos_status_created', 'videos', ['status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_favorites_user_created', 'favorites', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_comments_video_pinned_created', 'comments', ['video_id', sa.text('is_pinned DESC'), sa.text('created_at DESC')], unique=False)
    op.create_index('idx_comments_video_created', 'comments', ['video_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
