"""add admin user preferences (timezone, language, theme)

Revision ID: 98c4f79e2b55
Revises: addf2f792dce
Create Date: 2025-10-14 10:09:05.134162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98c4f79e2b55'
down_revision: Union[str, None] = 'addf2f792dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add admin user preferences
    op.add_column('admin_users', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('admin_users', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('admin_users', sa.Column('preferred_theme', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'preferred_theme')
    op.drop_column('admin_users', 'preferred_language')
    op.drop_column('admin_users', 'timezone')
    # ### end Alembic commands ###
