"""add_system_settings_table

Revision ID: 99205e9e5f56
Revises: 51a2a9318c9d
Create Date: 2025-10-09 18:32:31.138668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99205e9e5f56'
down_revision: Union[str, None] = '51a2a9318c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_url', sa.String(length=255), nullable=False),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('site_keywords', sa.String(length=500), nullable=True),
    sa.Column('site_logo', sa.String(length=500), nullable=True),
    sa.Column('site_favicon', sa.String(length=500), nullable=True),
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.String(length=500), nullable=True),
    sa.Column('upload_max_size', sa.Integer(), nullable=False),
    sa.Column('upload_allowed_formats', sa.JSON(), nullable=False),
    sa.Column('image_max_size', sa.Integer(), nullable=False),
    sa.Column('image_allowed_formats', sa.JSON(), nullable=False),
    sa.Column('video_auto_approve', sa.Boolean(), nullable=False),
    sa.Column('video_require_review', sa.Boolean(), nullable=False),
    sa.Column('video_default_quality', sa.String(length=20), nullable=False),
    sa.Column('video_enable_transcode', sa.Boolean(), nullable=False),
    sa.Column('video_transcode_formats', sa.JSON(), nullable=False),
    sa.Column('comment_enable', sa.Boolean(), nullable=False),
    sa.Column('comment_require_approval', sa.Boolean(), nullable=False),
    sa.Column('comment_allow_guest', sa.Boolean(), nullable=False),
    sa.Column('comment_max_length', sa.Integer(), nullable=False),
    sa.Column('user_enable_registration', sa.Boolean(), nullable=False),
    sa.Column('user_require_email_verification', sa.Boolean(), nullable=False),
    sa.Column('user_default_avatar', sa.String(length=500), nullable=True),
    sa.Column('user_max_favorites', sa.Integer(), nullable=False),
    sa.Column('security_enable_captcha', sa.Boolean(), nullable=False),
    sa.Column('security_login_max_attempts', sa.Integer(), nullable=False),
    sa.Column('security_login_lockout_duration', sa.Integer(), nullable=False),
    sa.Column('security_session_timeout', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('analytics_code', sa.Text(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('custom_js', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
