"""add danmaku and blocked_words tables

Revision ID: 9e912ccc1af8
Revises: 23014a639f71
Create Date: 2025-10-10 08:06:15.841588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e912ccc1af8'
down_revision: Union[str, None] = '23014a639f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_words_id'), 'blocked_words', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_words_word'), 'blocked_words', ['word'], unique=True)
    op.create_table('danmaku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('SCROLL', 'TOP', 'BOTTOM', name='danmakutype'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DELETED', name='danmakustatus'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danmaku_id'), 'danmaku', ['id'], unique=False)
    op.create_index(op.f('ix_danmaku_status'), 'danmaku', ['status'], unique=False)
    op.create_index(op.f('ix_danmaku_time'), 'danmaku', ['time'], unique=False)
    op.create_index(op.f('ix_danmaku_user_id'), 'danmaku', ['user_id'], unique=False)
    op.create_index(op.f('ix_danmaku_video_id'), 'danmaku', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_danmaku_video_id'), table_name='danmaku')
    op.drop_index(op.f('ix_danmaku_user_id'), table_name='danmaku')
    op.drop_index(op.f('ix_danmaku_time'), table_name='danmaku')
    op.drop_index(op.f('ix_danmaku_status'), table_name='danmaku')
    op.drop_index(op.f('ix_danmaku_id'), table_name='danmaku')
    op.drop_table('danmaku')
    op.drop_index(op.f('ix_blocked_words_word'), table_name='blocked_words')
    op.drop_index(op.f('ix_blocked_words_id'), table_name='blocked_words')
    op.drop_table('blocked_words')
    # ### end Alembic commands ###
