"""add_settings_enhancements

Revision ID: a9358ea4bc18
Revises: f0deea5e91de
Create Date: 2025-10-13 11:11:36.729731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9358ea4bc18'
down_revision: Union[str, None] = 'f0deea5e91de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to system_settings table
    op.add_column('system_settings', sa.Column('rate_limit_config', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('cache_config', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_test_email', sa.String(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_last_test_at', sa.DateTime(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_last_test_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'smtp_last_test_status')
    op.drop_column('system_settings', 'smtp_last_test_at')
    op.drop_column('system_settings', 'smtp_test_email')
    op.drop_column('system_settings', 'cache_config')
    op.drop_column('system_settings', 'rate_limit_config')
    # ### end Alembic commands ###
