"""add_data_scope_permission_tables

Revision ID: addf2f792dce
Revises: fd3b95489497
Create Date: 2025-10-14 04:51:13.113916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'addf2f792dce'
down_revision: Union[str, None] = 'fd3b95489497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='部门编码'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级,0为顶级'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='路径,如 1/2/3'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('data_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False, comment='范围类型: all(全部), department(本部门), department_and_children(本部门及下级), custom(自定义)'),
    sa.Column('department_ids', sa.Text(), nullable=True, comment='部门ID列表,JSON格式,如 [1,2,3]'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型: video, user, comment等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_scopes_id'), 'data_scopes', ['id'], unique=False)
    op.create_index(op.f('ix_data_scopes_role_id'), 'data_scopes', ['role_id'], unique=False)
    op.create_table('admin_user_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主要部门'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_departments_admin_user_id'), 'admin_user_departments', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_user_departments_department_id'), 'admin_user_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_admin_user_departments_id'), 'admin_user_departments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_departments_id'), table_name='admin_user_departments')
    op.drop_index(op.f('ix_admin_user_departments_department_id'), table_name='admin_user_departments')
    op.drop_index(op.f('ix_admin_user_departments_admin_user_id'), table_name='admin_user_departments')
    op.drop_table('admin_user_departments')
    op.drop_index(op.f('ix_data_scopes_role_id'), table_name='data_scopes')
    op.drop_index(op.f('ix_data_scopes_id'), table_name='data_scopes')
    op.drop_table('data_scopes')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
