"""add_permission_logs_table

Revision ID: da7a0e6c92ef
Revises: 81dc6d5bbe3a
Create Date: 2025-10-14 04:33:16.093047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da7a0e6c92ef'
down_revision: Union[str, None] = '81dc6d5bbe3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_logs_action'), 'permission_logs', ['action'], unique=False)
    op.create_index(op.f('ix_permission_logs_created_at'), 'permission_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_permission_logs_id'), 'permission_logs', ['id'], unique=False)
    op.create_index(op.f('ix_permission_logs_target_id'), 'permission_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_permission_logs_target_type'), 'permission_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_logs_target_type'), table_name='permission_logs')
    op.drop_index(op.f('ix_permission_logs_target_id'), table_name='permission_logs')
    op.drop_index(op.f('ix_permission_logs_id'), table_name='permission_logs')
    op.drop_index(op.f('ix_permission_logs_created_at'), table_name='permission_logs')
    op.drop_index(op.f('ix_permission_logs_action'), table_name='permission_logs')
    op.drop_table('permission_logs')
    # ### end Alembic commands ###
